package com.rokagram.entities;

public enum SystemSettingsEnum {
	INSTAGRAM_CLIENT_ID, INSTAGRAM_CLIENT_SECRET, INSTAGRAM_LOCALHOST_CLIENT_ID, INSTAGRAM_LOCALHOST_CLIENT_SECRET, TUMBLR_API_KEY, FEEDFM_BASIC_AUTH
}
